# Generated by Django 3.1.5 on 2021-02-03 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=5, null=True)),
                ('flag', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('match_start', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=128, null=True)),
                ('status_short', models.CharField(max_length=5, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('home_odds', models.FloatField(blank=True, null=True)),
                ('draw_odds', models.FloatField(blank=True, null=True)),
                ('away_odds', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pts_exact', models.IntegerField()),
                ('pts_difference', models.IntegerField()),
                ('pts_winner', models.IntegerField()),
                ('pts_wrong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_league_update', models.DateField()),
                ('next_fixture_update', models.DateField()),
                ('last_fixture_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipp_home', models.IntegerField()),
                ('tipp_away', models.IntegerField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.fixture')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.URLField(max_length=255, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.playerstatus')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(through='game.Player_Games', to='game.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('logo', models.URLField(max_length=255, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.country')),
                ('games', models.ManyToManyField(through='game.Game_Leagues', to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='game_leagues',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.league'),
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='game.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='leagues',
            field=models.ManyToManyField(through='game.Game_Leagues', to='game.League'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game.Player_Games', to='game.Player'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='game.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='game.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.league'),
        ),
    ]
