# Generated by Django 3.1.5 on 2021-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipp',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipp',
            name='yn_final',
            field=models.BooleanField(default=False),
        ),
    ]
